// C support: a generated main.c that reads the token stream from tokens.mjs,
// calls the solution's function and writes one JSON line per test.
// Signatures follow LeetCode's C conventions:
//   int[] nums        -> int* nums, int numsSize
//   int[][] grid      -> int** grid, int gridSize, int* gridColSize
//   string s          -> char* s            (NUL-terminated)
//   string[] words    -> char** words, int wordsSize
//   returns T[]       -> T* f(..., int* returnSize)
//   returns T[][]     -> T** f(..., int* returnSize, int** returnColumnSizes)
// Design problems (classes) aren't offered in C.
export { encodeTests } from "./tokens.mjs";

const SCALAR = {
  int: "int",
  long: "long long",
  double: "double",
  bool: "bool",
  char: "char",
  string: "char*",
  ListNode: "struct ListNode*",
  TreeNode: "struct TreeNode*",
};

const baseOf = (type) => type.replace(/(\[\])+$/, "");
const dimsOf = (type) => (type.length - baseOf(type).length) / 2;

export function supported(meta) {
  if (meta.kind !== "function") return false;
  const types = [...meta.signature.params.map((p) => p.type), meta.signature.returns];
  return types.every((t) => SCALAR[baseOf(t)] && dimsOf(t) <= 2);
}

const cType = (type) => SCALAR[baseOf(type)] + "*".repeat(dimsOf(type));

// The C parameter list for a signature, LeetCode style.
export function cParams(sig) {
  const params = sig.params.flatMap((p) => {
    const d = dimsOf(p.type);
    if (d === 0) return [`${cType(p.type)} ${p.name}`];
    if (d === 1) return [`${cType(p.type)} ${p.name}`, `int ${p.name}Size`];
    return [`${cType(p.type)} ${p.name}`, `int ${p.name}Size`, `int* ${p.name}ColSize`];
  });
  const r = dimsOf(sig.returns);
  if (r >= 1) params.push("int* returnSize");
  if (r === 2) params.push("int** returnColumnSizes");
  return params;
}

export const cReturn = (sig) => cType(sig.returns);

const PRELUDE = `// Generated by the Ren DSA pipeline. Do not edit.
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

struct ListNode {
  int val;
  struct ListNode* next;
};
struct TreeNode {
  int val;
  struct TreeNode* left;
  struct TreeNode* right;
};

#include "solution.c"

static long long rLong(void) { long long x = 0; if (scanf("%lld", &x) != 1) exit(3); return x; }
static int rInt(void) { return (int) rLong(); }
static double rDouble(void) { double x = 0; if (scanf("%lf", &x) != 1) exit(3); return x; }
static bool rBool(void) { return rLong() != 0; }
static char rChar(void) { return (char) rLong(); }
static char* rString(void) {
  long long n = rLong();
  getchar(); /* the space after the length */
  char* s = malloc((size_t) n + 1);
  if (n && fread(s, 1, (size_t) n, stdin) != (size_t) n) exit(3);
  s[n] = 0;
  return s;
}
static struct ListNode* rList(void) {
  long long n = rLong();
  struct ListNode dummy = {0, NULL}, *tail = &dummy;
  struct ListNode** nodes = malloc(sizeof(struct ListNode*) * (size_t) (n ? n : 1));
  for (long long i = 0; i < n; i++) {
    tail->next = calloc(1, sizeof(struct ListNode));
    tail = tail->next;
    tail->val = rInt();
    nodes[i] = tail;
  }
  long long at = rLong();
  if (at >= 0 && at < n) tail->next = nodes[at];
  free(nodes);
  return dummy.next;
}
static struct TreeNode* rTree(void) {
  long long n = rLong();
  struct TreeNode** slots = calloc((size_t) (n ? n : 1), sizeof(struct TreeNode*));
  for (long long i = 0; i < n; i++) {
    if (rLong()) { slots[i] = calloc(1, sizeof(struct TreeNode)); slots[i]->val = rInt(); }
  }
  struct TreeNode* root = n ? slots[0] : NULL;
  if (root) {
    struct TreeNode** q = malloc(sizeof(struct TreeNode*) * (size_t) n);
    long long head = 0, tailq = 0, i = 1;
    q[tailq++] = root;
    while (head < tailq && i < n) {
      struct TreeNode* node = q[head++];
      if (i < n) { node->left = slots[i]; if (slots[i]) q[tailq++] = slots[i]; i++; }
      if (i < n) { node->right = slots[i]; if (slots[i]) q[tailq++] = slots[i]; i++; }
    }
    free(q);
  }
  free(slots);
  return root;
}

static void wLong(long long x) { printf("%lld", x); }
static void wInt(int x) { printf("%d", x); }
static void wBool(bool x) { fputs(x ? "true" : "false", stdout); }
static void wDouble(double x) { printf("%.17g", x); }
static void wString(const char* s) {
  putchar('"');
  if (s) for (const unsigned char* p = (const unsigned char*) s; *p; p++) {
    if (*p == '"' || *p == '\\\\') { putchar('\\\\'); putchar(*p); }
    else if (*p == '\\n') fputs("\\\\n", stdout);
    else if (*p < 0x20) printf("\\\\u%04x", *p);
    else putchar(*p);
  }
  putchar('"');
}
static void wChar(char c) { char s[2] = {c, 0}; wString(s); }
static void wList(struct ListNode* node) {
  putchar('[');
  for (long k = 0; node; node = node->next, k++) {
    if (k > 2000000) { fputs("returned list is too long (a cycle?)", stderr); exit(4); }
    if (k) putchar(',');
    printf("%d", node->val);
  }
  putchar(']');
}
static void wTree(struct TreeNode* root) {
  size_t cap = 64, len = 0;
  struct TreeNode** order = malloc(sizeof(struct TreeNode*) * cap);
  order[len++] = root;
  for (size_t h = 0; h < len; h++) {
    if (!order[h]) continue;
    if (len + 2 > cap) { cap *= 2; order = realloc(order, sizeof(struct TreeNode*) * cap); }
    order[len++] = order[h]->left;
    order[len++] = order[h]->right;
  }
  while (len && !order[len - 1]) len--;
  putchar('[');
  for (size_t k = 0; k < len; k++) { if (k) putchar(','); if (order[k]) printf("%d", order[k]->val); else fputs("null", stdout); }
  putchar(']');
  free(order);
}

static double nowMs(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return ts.tv_sec * 1e3 + ts.tv_nsec / 1e6;
}
`;

const READ = { int: "rInt", long: "rLong", double: "rDouble", bool: "rBool", char: "rChar", string: "rString", ListNode: "rList", TreeNode: "rTree" };
const WRITE = { int: "wInt", long: "wLong", double: "wDouble", bool: "wBool", char: "wChar", string: "wString", ListNode: "wList", TreeNode: "wTree" };

// Reading one parameter into locals: the value, plus its sizes for arrays.
function readParam(p, i) {
  const base = baseOf(p.type);
  const t = SCALAR[base];
  const d = dimsOf(p.type);
  if (d === 0) return `    ${t} a${i} = ${READ[base]}();`;
  if (d === 1) {
    return [
      `    int a${i}n = rInt();`,
      `    ${t}* a${i} = malloc(sizeof(${t}) * (a${i}n ? a${i}n : 1));`,
      `    for (int k = 0; k < a${i}n; k++) a${i}[k] = ${READ[base]}();`,
    ].join("\n");
  }
  return [
    `    int a${i}n = rInt();`,
    `    ${t}** a${i} = malloc(sizeof(${t}*) * (a${i}n ? a${i}n : 1));`,
    `    int* a${i}c = malloc(sizeof(int) * (a${i}n ? a${i}n : 1));`,
    `    for (int k = 0; k < a${i}n; k++) {`,
    `      a${i}c[k] = rInt();`,
    `      a${i}[k] = malloc(sizeof(${t}) * (a${i}c[k] ? a${i}c[k] : 1));`,
    `      for (int j = 0; j < a${i}c[k]; j++) a${i}[k][j] = ${READ[base]}();`,
    `    }`,
  ].join("\n");
}

function callArgs(sig) {
  const args = sig.params.flatMap((p, i) => {
    const d = dimsOf(p.type);
    return d === 0 ? [`a${i}`] : d === 1 ? [`a${i}`, `a${i}n`] : [`a${i}`, `a${i}n`, `a${i}c`];
  });
  const r = dimsOf(sig.returns);
  if (r >= 1) args.push("&retN");
  if (r === 2) args.push("&retC");
  return args.join(", ");
}

function writeResult(type) {
  const base = baseOf(type);
  const w = WRITE[base];
  const d = dimsOf(type);
  if (d === 0) return `${w}(res);`;
  if (d === 1) return `putchar('['); for (int k = 0; k < retN; k++) { if (k) putchar(','); ${w}(res[k]); } putchar(']');`;
  return `putchar('['); for (int k = 0; k < retN; k++) { if (k) putchar(','); putchar('['); for (int j = 0; j < retC[k]; j++) { if (j) putchar(','); ${w}(res[k][j]); } putchar(']'); } putchar(']');`;
}

export function harness(meta) {
  if (!supported(meta)) throw new Error("C harness: this signature isn't supported in C");
  const sig = meta.signature;
  return `${PRELUDE}
int main(void) {
  int T = rInt();
  for (int t = 0; t < T; t++) {
    char* id = rString();
${sig.params.map(readParam).join("\n")}
    int retN = 0;
    int* retC = NULL;
    (void) retC;
    printf("{\\"start\\":"); wString(id); printf("}\\n");
    fflush(stdout);
    double t0 = nowMs();
    ${cReturn(sig)} res = ${sig.function}(${callArgs(sig)});
    double ms = nowMs() - t0;
    printf("\\n{\\"id\\":"); wString(id); printf(",\\"out\\":");
    ${writeResult(sig.returns)}
    printf(",\\"ms\\":%.3f}\\n", ms);
    fflush(stdout);
  }
  return 0;
}
`;
}
