// C++ support: generate a harness main() for a signature (function or design
// class) that reads the token stream from tokens.mjs, and a <bits/stdc++.h> shim
// (libc++ on macOS doesn't ship one, but many people start their solutions with it).
export { encodeTests } from "./tokens.mjs";

const CPP_TYPES = {
  int: "int",
  long: "long long",
  double: "double",
  bool: "bool",
  char: "char",
  string: "string",
  ListNode: "ListNode*",
  TreeNode: "TreeNode*",
  RandomNode: "RandomNode*",
};

export function cppType(type) {
  const base = type.replace(/(\[\])+$/, "");
  const depth = (type.length - base.length) / 2;
  let t = CPP_TYPES[base];
  if (!t) throw new Error(`C++ harness: type ${type} isn't supported`);
  for (let i = 0; i < depth; i++) t = `vector<${t}>`;
  return t;
}

const PRELUDE = `// Generated by the Ren DSA pipeline. Do not edit.
#include <bits/stdc++.h>
using namespace std;

struct ListNode {
  int val;
  ListNode* next;
  ListNode() : val(0), next(nullptr) {}
  ListNode(int x) : val(x), next(nullptr) {}
  ListNode(int x, ListNode* next) : val(x), next(next) {}
};
struct RandomNode {
  int val;
  RandomNode* next;
  RandomNode* random;
  RandomNode() : val(0), next(nullptr), random(nullptr) {}
  RandomNode(int x) : val(x), next(nullptr), random(nullptr) {}
};
struct TreeNode {
  int val;
  TreeNode* left;
  TreeNode* right;
  TreeNode() : val(0), left(nullptr), right(nullptr) {}
  TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
  TreeNode(int x, TreeNode* left, TreeNode* right) : val(x), left(left), right(right) {}
};

#include "solution.cpp"

template <class T> struct R;
template <> struct R<int> { static int get() { long long x; cin >> x; return (int)x; } };
template <> struct R<long long> { static long long get() { long long x; cin >> x; return x; } };
template <> struct R<double> { static double get() { double x; cin >> x; return x; } };
template <> struct R<bool> { static bool get() { int x; cin >> x; return x != 0; } };
template <> struct R<char> { static char get() { int x; cin >> x; return (char)x; } };
template <> struct R<string> {
  static string get() { size_t n; cin >> n; cin.get(); string s(n, '\\0'); if (n) cin.read(&s[0], n); return s; }
};
template <class T> struct R<vector<T>> {
  static vector<T> get() { size_t n; cin >> n; vector<T> v; v.reserve(n); for (size_t i = 0; i < n; i++) v.push_back(R<T>::get()); return v; }
};
template <> struct R<ListNode*> {
  static ListNode* get() {
    size_t n; cin >> n;
    ListNode dummy; ListNode* tail = &dummy; vector<ListNode*> nodes;
    for (size_t i = 0; i < n; i++) { int v; cin >> v; tail = tail->next = new ListNode(v); nodes.push_back(tail); }
    long long at; cin >> at;
    static vector<ListNode*> prev;  // the list read just before, for joins
    if (at >= 0 && at < (long long)n) tail->next = nodes[at];
    if (at <= -2 && -2 - at < (long long)prev.size()) tail->next = prev[-2 - at];
    prev = nodes;
    return dummy.next;
  }
};
static unordered_set<RandomNode*> givenRandom;  // every input node, so a copy can be told apart
template <> struct R<RandomNode*> {
  static RandomNode* get() {
    size_t n; cin >> n;
    vector<RandomNode*> nodes(n);
    vector<long long> rnd(n);
    for (size_t i = 0; i < n; i++) { int v; cin >> v >> rnd[i]; nodes[i] = new RandomNode(v); givenRandom.insert(nodes[i]); }
    for (size_t i = 0; i < n; i++) { if (i + 1 < n) nodes[i]->next = nodes[i + 1]; nodes[i]->random = rnd[i] >= 0 ? nodes[rnd[i]] : nullptr; }
    return n ? nodes[0] : nullptr;
  }
};
template <> struct R<TreeNode*> {
  static TreeNode* get() {
    size_t n; cin >> n;
    vector<TreeNode*> slots(n, nullptr);
    for (size_t i = 0; i < n; i++) { int has; cin >> has; if (has) { int v; cin >> v; slots[i] = new TreeNode(v); } }
    if (!n || !slots[0]) return nullptr;
    size_t i = 1;
    deque<TreeNode*> q{slots[0]};
    while (!q.empty() && i < n) {
      TreeNode* node = q.front(); q.pop_front();
      if (i < n) { node->left = slots[i]; if (slots[i]) q.push_back(slots[i]); i++; }
      if (i < n) { node->right = slots[i]; if (slots[i]) q.push_back(slots[i]); i++; }
    }
    return slots[0];
  }
};

static void W(ostream& o, int x) { o << x; }
static void W(ostream& o, long long x) { o << x; }
static void W(ostream& o, bool x) { o << (x ? "true" : "false"); }
static void W(ostream& o, double x) { char b[40]; snprintf(b, sizeof b, "%.17g", x); o << b; }
static void W(ostream& o, const string& s) {
  o << '"';
  for (unsigned char c : s) {
    if (c == '"' || c == '\\\\') o << '\\\\' << c;
    else if (c == '\\n') o << "\\\\n";
    else if (c < 0x20) { char b[8]; snprintf(b, sizeof b, "\\\\u%04x", c); o << b; }
    else o << c;
  }
  o << '"';
}
static void W(ostream& o, char c) { W(o, string(1, c)); }
static void W(ostream& o, ListNode* node) {
  o << '[';
  for (size_t k = 0; node; node = node->next, k++) {
    if (k > 2000000) throw runtime_error("returned list is too long (a cycle?)");
    if (k) o << ',';
    o << node->val;
  }
  o << ']';
}
static void W(ostream& o, RandomNode* head) {
  vector<RandomNode*> order;
  unordered_map<RandomNode*, size_t> at;
  for (RandomNode* p = head; p; p = p->next) {
    if (order.size() > 2000000) throw runtime_error("returned list is too long (a cycle?)");
    if (givenRandom.count(p)) throw runtime_error("the answer reuses an original node; build new nodes");
    at[p] = order.size();
    order.push_back(p);
  }
  o << '[';
  for (size_t k = 0; k < order.size(); k++) {
    if (k) o << ',';
    o << '[' << order[k]->val << ',';
    if (!order[k]->random) o << "null";
    else if (at.count(order[k]->random)) o << at[order[k]->random];
    else throw runtime_error("a random pointer leads outside the returned list");
    o << ']';
  }
  o << ']';
}
static void W(ostream& o, TreeNode* root) {
  vector<TreeNode*> order{root};
  for (size_t h = 0; h < order.size(); h++) if (order[h]) { order.push_back(order[h]->left); order.push_back(order[h]->right); }
  while (!order.empty() && !order.back()) order.pop_back();
  o << '[';
  for (size_t k = 0; k < order.size(); k++) { if (k) o << ','; if (order[k]) o << order[k]->val; else o << "null"; }
  o << ']';
}
template <class T> static void W(ostream& o, const vector<T>& v) {
  o << '[';
  for (size_t i = 0; i < v.size(); i++) { if (i) o << ','; W(o, v[i]); }
  o << ']';
}
`;

function functionMain(sig) {
  const reads = sig.params.map((p, i) => `    ${cppType(p.type)} a${i} = R<${cppType(p.type)}>::get();`).join("\n");
  const args = sig.params.map((_, i) => `a${i}`).join(", ");
  return `
int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  int T; cin >> T;
  for (int t = 0; t < T; t++) {
    string id = R<string>::get();
${reads}
    cout << "{\\"start\\":"; W(cout, id); cout << "}" << endl;
    auto t0 = chrono::steady_clock::now();
    auto out = Solution().${sig.function}(${args});
    double ms = chrono::duration<double, milli>(chrono::steady_clock::now() - t0).count();
    cout << "\\n{\\"id\\":"; W(cout, id); cout << ",\\"out\\":"; W(cout, out);
    cout << ",\\"ms\\":" << fixed << setprecision(3) << ms << defaultfloat << "}" << endl;
  }
}
`;
}

function designMain(design) {
  const ctorReads = design.constructor.params.map((p, i) => `    ${cppType(p.type)} c${i} = R<${cppType(p.type)}>::get();`).join("\n");
  const ctorArgs = design.constructor.params.map((_, i) => `c${i}`).join(", ");
  // Every call is parsed into a closure first, so the timer measures only the solution.
  const branches = design.methods
    .map((m) => {
      const reads = m.params.map((p, i) => `${cppType(p.type)} a${i} = R<${cppType(p.type)}>::get();`).join(" ");
      const args = m.params.map((_, i) => `a${i}`).join(", ");
      const caps = ["&obj", ...m.params.map((_, i) => `a${i}`)].join(", ");
      const body = m.returns === "void" ? `obj->${m.name}(${args}); res << "null";` : `W(res, obj->${m.name}(${args}));`;
      return `      if (m == "${m.name}") { ${reads} ops.push_back([${caps}](ostream& res) mutable { ${body} }); }`;
    })
    .join("\n      else\n");
  return `
int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  int T; cin >> T;
  for (int t = 0; t < T; t++) {
    string id = R<string>::get();
    int C; cin >> C;
${ctorReads}
    ${design.class}* obj = nullptr;
    vector<function<void(ostream&)>> ops;
    ops.reserve(C);
    for (int c = 1; c < C; c++) {
      string m = R<string>::get();
${branches}
      else throw runtime_error("unknown method " + m);
    }
    cout << "{\\"start\\":"; W(cout, id); cout << "}" << endl;
    ostringstream res;
    auto t0 = chrono::steady_clock::now();
    obj = new ${design.class}(${ctorArgs});
    res << "[null";
    for (auto& op : ops) { res << ','; op(res); }
    res << ']';
    double ms = chrono::duration<double, milli>(chrono::steady_clock::now() - t0).count();
    cout << "\\n{\\"id\\":"; W(cout, id); cout << ",\\"out\\":" << res.str();
    cout << ",\\"ms\\":" << fixed << setprecision(3) << ms << defaultfloat << "}" << endl;
  }
}
`;
}

export function harness(meta) {
  return PRELUDE + (meta.kind === "design" ? designMain(meta.design) : functionMain(meta.signature));
}

// Everything a solution might reasonably include, for code that starts with <bits/stdc++.h>.
export const BITS_STDCXX = `#pragma once
#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <chrono>
#include <climits>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <queue>
#include <random>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
`;
