// Java support: a generated Main.java that reads the token stream from
// tokens.mjs, calls the solution (class Solution, or a design class) and
// writes one JSON line per test, like the other runners. Solutions use
// arrays for list types (int[], int[][], String[]), as LeetCode's Java does.
export { encodeTests } from "./tokens.mjs";

const JAVA_TYPES = {
  int: "int",
  long: "long",
  double: "double",
  bool: "boolean",
  char: "char",
  string: "String",
  ListNode: "ListNode",
  TreeNode: "TreeNode",
  RandomNode: "RandomNode",
};

export function javaType(type) {
  const base = type.replace(/(\[\])+$/, "");
  const t = JAVA_TYPES[base];
  if (!t) throw new Error(`Java harness: type ${type} isn't supported`);
  return t + type.slice(base.length);
}

// What LeetCode's Java has without importing. Kept on one line in front of
// the solution's first line, so compile errors keep their line numbers.
export const JAVA_IMPORTS = "import java.util.*; import java.util.function.*; import java.util.stream.*; import java.math.*; ";

// A reader method per type the signature uses, e.g. r_int_2() for int[][].
function readers(types) {
  const out = new Map();
  const add = (type) => {
    const name = readerName(type);
    if (out.has(name) || !type.endsWith("[]")) return;
    const inner = type.slice(0, -2);
    add(inner);
    const base = JAVA_TYPES[type.replace(/(\[\])+$/, "")];
    const dims = (type.length - type.replace(/(\[\])+$/, "").length) / 2;
    out.set(
      name,
      `  static ${javaType(type)} ${name}() throws IOException { int n = (int) in.nextLong(); ${javaType(type)} a = new ${base}[n]${"[]".repeat(dims - 1)}; for (int i = 0; i < n; i++) a[i] = ${readerName(inner)}(); return a; }`
    );
  };
  types.forEach(add);
  return [...out.values()].join("\n");
}

function readerName(type) {
  const base = type.replace(/(\[\])+$/, "");
  const dims = (type.length - base.length) / 2;
  const scalar = { int: "rInt", long: "rLong", double: "rDouble", bool: "rBool", char: "rChar", string: "rString", ListNode: "rList", TreeNode: "rTree", RandomNode: "rRandom" }[base];
  if (!scalar) throw new Error(`Java harness: type ${type} isn't supported`);
  return dims ? `r_${base}_${dims}` : scalar;
}

const PRELUDE = `// Generated by the Ren DSA pipeline. Do not edit.
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

class RandomNode {
  int val;
  RandomNode next;
  RandomNode random;
  RandomNode() {}
  RandomNode(int val) { this.val = val; }
}
class ListNode {
  int val;
  ListNode next;
  ListNode() {}
  ListNode(int val) { this.val = val; }
  ListNode(int val, ListNode next) { this.val = val; this.next = next; }
}

class TreeNode {
  int val;
  TreeNode left;
  TreeNode right;
  TreeNode() {}
  TreeNode(int val) { this.val = val; }
  TreeNode(int val, TreeNode left, TreeNode right) { this.val = val; this.left = left; this.right = right; }
}

// Reads the token stream: whitespace-separated numbers, strings as "<bytes> <text>".
class Tokens {
  private final InputStream in = new BufferedInputStream(System.in, 1 << 16);
  private int peek() throws IOException { in.mark(1); int c = in.read(); in.reset(); return c; }
  private String token() throws IOException {
    int c;
    while ((c = in.read()) != -1 && Character.isWhitespace(c)) {}
    StringBuilder sb = new StringBuilder();
    while (c != -1 && !Character.isWhitespace(c)) { sb.append((char) c); c = in.read(); }
    return sb.toString();
  }
  long nextLong() throws IOException { return Long.parseLong(token()); }
  double nextDouble() throws IOException { return Double.parseDouble(token()); }
  String nextString() throws IOException {
    int n = Integer.parseInt(token());
    byte[] b = new byte[n];
    int off = 0;
    while (off < n) { int k = in.read(b, off, n - off); if (k < 0) break; off += k; }
    return new String(b, StandardCharsets.UTF_8);
  }
}

public class Main {
  static final Tokens in = new Tokens();
  // The solution's own prints share this stream, so they stay in order.
  static final PrintStream out = System.out;

  static int rInt() throws IOException { return (int) in.nextLong(); }
  static long rLong() throws IOException { return in.nextLong(); }
  static double rDouble() throws IOException { return in.nextDouble(); }
  static boolean rBool() throws IOException { return in.nextLong() != 0; }
  static char rChar() throws IOException { return (char) in.nextLong(); }
  static String rString() throws IOException { return in.nextString(); }
  static ListNode rList() throws IOException {
    int n = (int) in.nextLong();
    ListNode dummy = new ListNode(), tail = dummy;
    List<ListNode> nodes = new ArrayList<>();
    for (int i = 0; i < n; i++) { tail = tail.next = new ListNode((int) in.nextLong()); nodes.add(tail); }
    long at = in.nextLong();
    if (at >= 0 && at < n) tail.next = nodes.get((int) at);
    if (at <= -2 && -2 - at < prevList.size()) tail.next = prevList.get((int) (-2 - at));
    prevList = nodes;
    return dummy.next;
  }
  static List<ListNode> prevList = new ArrayList<>();  // the list read just before, for joins
  static Set<RandomNode> givenRandom = Collections.newSetFromMap(new IdentityHashMap<>());
  static RandomNode rRandom() throws IOException {
    int n = (int) in.nextLong();
    RandomNode[] nodes = new RandomNode[n];
    long[] rnd = new long[n];
    for (int i = 0; i < n; i++) { nodes[i] = new RandomNode((int) in.nextLong()); rnd[i] = in.nextLong(); givenRandom.add(nodes[i]); }
    for (int i = 0; i < n; i++) { if (i + 1 < n) nodes[i].next = nodes[i + 1]; nodes[i].random = rnd[i] >= 0 ? nodes[(int) rnd[i]] : null; }
    return n > 0 ? nodes[0] : null;
  }
  static TreeNode rTree() throws IOException {
    int n = (int) in.nextLong();
    TreeNode[] slots = new TreeNode[n];
    for (int i = 0; i < n; i++) if (in.nextLong() != 0) slots[i] = new TreeNode((int) in.nextLong());
    if (n == 0 || slots[0] == null) return null;
    ArrayDeque<TreeNode> q = new ArrayDeque<>();
    q.add(slots[0]);
    int i = 1;
    while (!q.isEmpty() && i < n) {
      TreeNode node = q.poll();
      if (i < n) { node.left = slots[i]; if (slots[i] != null) q.add(slots[i]); i++; }
      if (i < n) { node.right = slots[i]; if (slots[i] != null) q.add(slots[i]); i++; }
    }
    return slots[0];
  }

  static void W(StringBuilder sb, String s) {
    sb.append('"');
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      if (c == '"' || c == '\\\\') sb.append('\\\\').append(c);
      else if (c == '\\n') sb.append("\\\\n");
      else if (c < 0x20) sb.append(String.format("\\\\u%04x", (int) c));
      else sb.append(c);
    }
    sb.append('"');
  }

  // Any answer as JSON: primitives arrive boxed, arrays of any depth recurse.
  static void W(StringBuilder sb, Object o) {
    if (o == null) sb.append("null");
    else if (o instanceof String s) W(sb, s);
    else if (o instanceof Character c) W(sb, String.valueOf(c));
    else if (o instanceof Boolean b) sb.append(b ? "true" : "false");
    else if (o instanceof Double d) sb.append(d.isNaN() || d.isInfinite() ? "null" : Double.toString(d));
    else if (o instanceof Float f) sb.append(Double.toString(f.doubleValue()));
    else if (o instanceof Number n) sb.append(n.longValue());
    else if (o instanceof ListNode node) {
      sb.append('[');
      for (int k = 0; node != null; node = node.next, k++) {
        if (k > 2000000) throw new RuntimeException("returned list is too long (a cycle?)");
        if (k > 0) sb.append(',');
        sb.append(node.val);
      }
      sb.append(']');
    } else if (o instanceof RandomNode head) {
      List<RandomNode> order = new ArrayList<>();
      Map<RandomNode, Integer> at = new IdentityHashMap<>();
      for (RandomNode p = head; p != null; p = p.next) {
        if (order.size() > 2000000) throw new RuntimeException("returned list is too long (a cycle?)");
        if (givenRandom.contains(p)) throw new RuntimeException("the answer reuses an original node; build new nodes");
        at.put(p, order.size());
        order.add(p);
      }
      sb.append('[');
      for (int k = 0; k < order.size(); k++) {
        if (k > 0) sb.append(',');
        RandomNode p = order.get(k);
        sb.append('[').append(p.val).append(',');
        if (p.random == null) sb.append("null");
        else if (at.containsKey(p.random)) sb.append(at.get(p.random));
        else throw new RuntimeException("a random pointer leads outside the returned list");
        sb.append(']');
      }
      sb.append(']');
    } else if (o instanceof TreeNode root) {
      List<TreeNode> order = new ArrayList<>();
      order.add(root);
      for (int h = 0; h < order.size(); h++) { TreeNode t = order.get(h); if (t != null) { order.add(t.left); order.add(t.right); } }
      while (!order.isEmpty() && order.get(order.size() - 1) == null) order.remove(order.size() - 1);
      sb.append('[');
      for (int k = 0; k < order.size(); k++) { if (k > 0) sb.append(','); TreeNode t = order.get(k); sb.append(t == null ? "null" : String.valueOf(t.val)); }
      sb.append(']');
    } else if (o.getClass().isArray()) {
      int n = java.lang.reflect.Array.getLength(o);
      sb.append('[');
      for (int i = 0; i < n; i++) { if (i > 0) sb.append(','); W(sb, java.lang.reflect.Array.get(o, i)); }
      sb.append(']');
    } else if (o instanceof Iterable<?> it) {
      sb.append('[');
      boolean first = true;
      for (Object x : it) { if (!first) sb.append(','); first = false; W(sb, x); }
      sb.append(']');
    } else throw new RuntimeException("can't write a " + o.getClass().getSimpleName());
  }

  static String json(String s) { StringBuilder sb = new StringBuilder(); W(sb, s); return sb.toString(); }

  static String error(Throwable e) {
    if (e instanceof StackOverflowError) return "StackOverflowError: recursion too deep";
    String msg = e.getMessage();
    StackTraceElement at = null;
    for (StackTraceElement el : e.getStackTrace()) if (el.getFileName() != null && el.getFileName().equals("Solution.java")) { at = el; break; }
    return e.getClass().getSimpleName() + (msg == null ? "" : ": " + msg) + (at == null ? "" : " (line " + at.getLineNumber() + ")");
  }

  // A deep stack for recursive solutions, as on LeetCode.
  public static void main(String[] args) throws Exception {
    Thread t = new Thread(null, () -> {
      try { run(); } catch (IOException e) { throw new UncheckedIOException(e); }
    }, "main", 1L << 29);
    t.start();
    t.join();
  }
`;

function functionRun(sig) {
  const types = sig.params.map((p) => p.type);
  const reads = sig.params.map((p, i) => `      ${javaType(p.type)} a${i} = ${readerName(p.type)}();`).join("\n");
  const args = sig.params.map((_, i) => `a${i}`).join(", ");
  // An empty list or tree comes back as null; the answer is still [].
  const emptyNode = ["ListNode", "TreeNode", "RandomNode"].includes(sig.returns) ? 'if (res == null) sb.append("[]"); else ' : "";
  return `${readers(types)}

  static void run() throws IOException {
    int T = (int) in.nextLong();
    for (int t = 0; t < T; t++) {
      String id = in.nextString();
${reads}
      out.println("{\\"start\\":" + json(id) + "}");
      out.flush();
      try {
        long t0 = System.nanoTime();
        Object res = new Solution().${sig.function}(${args});
        double ms = (System.nanoTime() - t0) / 1e6;
        StringBuilder sb = new StringBuilder("{\\"id\\":" + json(id) + ",\\"out\\":");
        ${emptyNode}W(sb, res);
        sb.append(String.format(Locale.ROOT, ",\\"ms\\":%.3f}", ms));
        out.println("\\n" + sb);
        out.flush();
      } catch (Throwable e) {
        out.println("\\n{\\"id\\":" + json(id) + ",\\"error\\":" + json(error(e)) + "}");
        out.flush();
      }
    }
  }
}
`;
}

function designRun(design) {
  const types = [...design.constructor.params, ...design.methods.flatMap((m) => m.params)].map((p) => p.type);
  const ctorReads = design.constructor.params.map((p, i) => `      ${javaType(p.type)} c${i} = ${readerName(p.type)}();`).join("\n");
  const ctorArgs = design.constructor.params.map((_, i) => `c${i}`).join(", ");
  // Every call is read into a closure first, so the timer measures only the solution.
  const branches = design.methods
    .map((m) => {
      const reads = m.params.map((p, i) => `final ${javaType(p.type)} a${i} = ${readerName(p.type)}();`).join(" ");
      const args = m.params.map((_, i) => `a${i}`).join(", ");
      const call = m.returns === "void" ? `{ obj[0].${m.name}(${args}); return null; }` : `obj[0].${m.name}(${args})`;
      return `        if (m.equals("${m.name}")) { ${reads} ops.add(() -> ${call}); }`;
    })
    .join("\n        else\n");
  return `${readers(types)}

  interface Op { Object call(); }

  static void run() throws IOException {
    int T = (int) in.nextLong();
    for (int t = 0; t < T; t++) {
      String id = in.nextString();
      int C = (int) in.nextLong();
${ctorReads}
      final ${design.class}[] obj = new ${design.class}[1];
      List<Op> ops = new ArrayList<>();
      for (int c = 1; c < C; c++) {
        String m = in.nextString();
${branches}
        else throw new RuntimeException("unknown method " + m);
      }
      out.println("{\\"start\\":" + json(id) + "}");
      out.flush();
      try {
        StringBuilder res = new StringBuilder("[null");
        long t0 = System.nanoTime();
        obj[0] = new ${design.class}(${ctorArgs});
        for (Op op : ops) { res.append(','); W(res, op.call()); }
        double ms = (System.nanoTime() - t0) / 1e6;
        res.append(']');
        out.println("\\n{\\"id\\":" + json(id) + ",\\"out\\":" + res + String.format(Locale.ROOT, ",\\"ms\\":%.3f}", ms));
        out.flush();
      } catch (Throwable e) {
        out.println("\\n{\\"id\\":" + json(id) + ",\\"error\\":" + json(error(e)) + "}");
        out.flush();
      }
    }
  }
}
`;
}

export function harness(meta) {
  return PRELUDE + (meta.kind === "design" ? designRun(meta.design) : functionRun(meta.signature));
}
